spring:
  application:
    name: order  #对应配置服务名  /{name}-{profiles}.yml     /{label}/{name}-{profiles}.yml
#PRODUCT:
 # ribbon:
  #  NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
   # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #改变ribbon负载均衡规则
server:
   port: 8084
env: dev2
